# Generated by Django 5.2.4 on 2025-07-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_basic', models.FloatField()),
                ('price_sale', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('feedbacks', models.IntegerField(default=0)),
                ('image', models.ImageField(default='product/default.png', upload_to='product/')),
            ],
        ),
    ]
